version: "3.7"
services:
  myto-do-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Khushbu@123
      MYSQL_DATABASE: ToDoDB
    volumes:
      - ./mysq-data:/var/lib/mysql
      - ./mysql-vol:/docker-entrypoint-initdb.d # Volume for initialization scripts
     # - ./mysql-data:/var/lib/mysql  # Persistent data

     

