name: Automate .NET and Docker CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ICU dependencies
        run: sudo apt-get update && sudo apt-get install -y libicu-dev

      - name: Set Invariant Globalization Mode
        run: echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1" >> $GITHUB_ENV

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: cd ToDoAPI/ && dotnet restore

      - name: Build .Net Core
        run: cd ToDoAPI/ && dotnet build --configuration Release --no-restore

      # - name: Build and Push the Docker image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: khushbumodi/todoapp
      #     tags: v1, latest
      #     registry: docker.io
      #     dockerfile: Dockerfile
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: cd ToDoAPI/ && docker build -t khushbumodi/todoapp:${{ github.sha }} -f Dockerfile .

      - name: Push Docker Image
        run: cd ToDoAPI/ && docker push khushbumodi/todoapp:${{ github.sha }}